export const easterEgg = () => {
  console.log(
    [
      '%c                                                                                                 ',
      '                                            LDDG                                                 ',
      '                                          DDDDDDDDL                                              ',
      '                                        GDDDDjtfDDDD                                             ',
      '                                       DDDGiiiiiijDDD                  LDDDDDDD                  ',
      '                                      DDDiiiiiiiiiiDDG               DDDDDDDDDDD                 ',
      '                                    DDDiiiiiiiiiiiiijDD          DDDDfiiiiiiiiiDD                ',
      '                                   LDDiiiiiiiitLDDDDDDDDDDDDDDDDDDDjiiiiiiiiiiiDDG               ',
      '                                  DDDiiiiifDDDDfiiiiiiiiiiiiiijDDDDDDiiiiiiiiiiiDD               ',
      '       ,                         GDDiiGDDDDDiiiiiiiiiiiiiiiiiiiiitDDDDDiiiiiiiiiDD               ',
      '         t                       DDiDDDDDiiiiiiiiiiiiiiiiiiiiiiiiiiiGDDDfiiiiiiiLDG              ',
      '          ,                     DDDDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDDDiiiiiiDD              ',
      '         ,,                    DDDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDDDiiiiiDD              ',
      '        ,,,                    DDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLDDtiiiDDL             ',
      '       i,,                    DDGiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifDDjiiLDG             ',
      '       ,;                    DDLiiiiiiiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiijDDjitDD             ',
      '       ,                    DDDiiiiiiiiLDDDiiiiiiiiiiiiiiiitfiiiiiijDiiiiiiiitDDtiDD             ',
      '       ,                    DDiiiiiiDDDDDDiiiijDiiiiDDiiiiiDDiiiiiiGDDtiiiiiiijDDiDD             ',
      '       ,f                  DDjiiiiiiDDDjiiiiiiGDLiGDDDiiiiDDDiiiiiiifDDDDLiiiiiGDDDD             ',
      '         ;,               GDLiiiiiiiiiiiiiiiiiiiGDGiitDDDDLiiiiiiiiiiiiiiiiiiiiiiDDD             ',
      '          f,              DDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDD             ',
      '          ,;              DDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDDG            ',
      '         ti               DDtiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDDL           ',
      '         DDD              GDGiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifDD           ',
      '        GDjDG              DDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDD           ',
      '        DDDDD              GDGiiiiiiiiiiiiiiiiiiiDDDDDDDGiiiiiiiiiiiiiiiiiiiiiiiiiiiGDG          ',
      '        DDLDD              DDfiiiiiiiiiiiiiiiDDDDDiiDDiiDDDDDDiiiiiiiiiiiiiiiiiiiiiifDD          ',
      '        DDLDD              DDiiiiiiiiiiiiiiiitDfiiiiDDiiiLDDGiiiiiiiiiiiiiiiiiiiiiiifDD          ',
      '        DDLDD              DDiiiiiiiiiiiiiiiiiiiiiiLDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiijDD          ',
      '        DDDDDGGGG         GDfiiiiiiiiiiiiiiiiiiiiiGDDDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDD          ',
      '    DDDDDDDDDDDDDD        DDiiiiiiiiiiiiiiiiiiDDDDDD:DDDiiiiiiiiiiiiiiiiiiiiiiiiiiiiiDD          ',
      '   GDDDDLfiijjjLDDD       DDiiiiiiiiiiiiiiiiiiDDDDD   GDDDDDGiiiiiiiiiiiiiiiiiiiiiiiiGDG         ',
      '   DDi:::::::::::DD       DDiiiiiiiiiiiiiiiii          iDDDDt;iiiiiiiiiiiiiiiiiiiiiitjDD         ',
      '   GDt:::::::::::DD       DDiiiiiiiiiiiiiii,                   iiiiiiiiiiiiiiiiiiiiiijDDG        ',
      '   LDD:::::::::::DD       DDiiiiiiiiiiiDDi,                     iijDiiiiiiiiiiiiiiiiiiiDD        ',
      '    DDD::::::::;DDL       DDiiiiiiiiiiiiLDDL                  DDDDDiiiiiiiiiiiiiiiiiiiitDD       ',
      '     DDDf::::iDDDG        DDfiiiiiiiiiiiiiDD                 DDDDDiiiiiiiiiiiiiiiiiiiiiiDD       ',
      '      DDDDDDDDDDL         LDDiiiiiiiiiiiiijDf                DDiiiiiiiiiiiiiiiiiiiiiiiiiDD       ',
      '        DDDDDDL            DDiiiiiiifDiiiiLDt                DDiiiitDGiiiiiiiiiiiiiiiiiDDG       ',
      '                         DDLDDiiiiiiitDDDDDi.                 GDDDDDiiiiiiiiiiiiiiiiiDDDDDDL     ',
      '                      DDDL,,GDDiiiiiiiiiiiiiiii, DDD;         iiiiiiiiiiiiiiiiiiiiitDDD,,DDDG    ',
      '                     DDD,,,,,DDDiiiiiiiiiiiiiiiitDDDDD    :DDLiiiiiiiiiiiiiiiiiiiiDDDD,,,,tDDG   ',
      '                    DDD,,,,,,,DDDiiiiiiiiiiiiiiiiiiiDDD iDDDDiiiiiiiiiiiiiiiiiiiGDDDt,,,,,,;DD   ',
      '                    DD,,,,,,,,,DDDDiiiiiiiiiiiiiiiiiiDDDDDDiiiiiiiiiiiiiiiiiitDDDDD,,,,,,,,,fDD  ',
      '                   GDG,,,,,,,,,,LDDDDDDGfiiiiiiiiiiiiiDDDiiiiiiiiiiiiiiiitGDDDDDD,,,,,,,,,,,,DD  ',
      '                   DDi,,,,,,,,,,,,fDDDDDDDDDDDDDDLtiitDDDiiittffGGDDDDDDDDDDDDt,,,,,,,,,,,,,,DD  ',
      '                   DDt,,,,,,,,,,,,,,,,,iLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDj,,,,,,,,,,,,,,,,,,DD  ',
      '                   GDG,,,,,,,,,,,,,,,,,,,,,,,,,,ijLDDLi,jDDDLLjjii,,,,,,,,,,,,,,,,,,,,,,,,,,,DD  ',
      '                    DD,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;DD  ',
      '                    LDDf,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,GDDD   ',
      '                     GDDDi,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;LDDDDD    ',
      '                      LDDDDDL,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ijjGDDDDDDDDDDDDD      ',
      '                        GDDDDDDDDDLti,,,,,,,,,iiitjjLLLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDG         ',
      '                            GDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD                                 ',
      '                                                                                                 '
    ].join('\n'),
    'font-family: monospace; color: white;font-weight:bold;background-image: linear-gradient(to right, DeepSkyBlue, darkTurquoise, darkTurquoise, royalBlue)'
  );
};
